[package]
name = "neural_networks"
version = "0.1.0"
edition = "2024"

[dependencies]
smallvec = { workspace = true }
candle-core = { workspace = true }
ndarray-rand = { workspace = true }
rand = { workspace = true }
rand_distr = { workspace = true }
utils = { workspace = true }
data_process = { workspace = true }
